site_name: Jeongsoo Pang

theme:
  name: material
  features:
    - navigation.tabs           # top tabs in the blue bar
    - navigation.tabs.sticky    # keep tabs visible on scroll
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections        # shows each top group as its own block in the sidebar
    - navigation.path
    - toc.integrate
    - toc.follow                # highlight active section in the right ToC
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.css
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.arithmatex:
      generic: true          # keep this
  - admonition
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax-config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/refresh-mathjax.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js
  - javascripts/katex-render.js
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.js
  - javascripts/history-map.js

nav:
  - Projects:
      - "0. Overview": portfolio/index.md
      - "1. Cercare-Medical": index.md
      - "2. Anti-Drone": anti_drone.md
      - "3. Remote Feeling Mimicking Chair": remote_chair.md
  - CV: cv.md
  - OS:
      - "0. Overview": os/index.md
      - "1. OS Overview": os/os_overview.md
      - "2. Process and Threads": os/lec2_process_thread.md
      - "3. IPC": os/lec3_ipc_synchronization.md
      - "4. Scheduling": os/lec4_scheduling.md  
      - "5. Deadlocks": os/lec5_deadlocks.md
  - Bayesian:
      - "0. Overview": bayesian/index.md
      - "1. Foundations": bayesian/lec1_foundations.md
      - "2. MLE": bayesian/lec2_mle_review.md
      - "3. Prior and Bayesian": bayesian/lec3_priors_logic.md
      - "4. Priors Details": bayesian/lec4_priors_types.md
      - "5. Posterior inference": bayesian/lec5_posterior-inference.md
      - "6. Interval Prediction": bayesian/lec6_intervals-prediction.md
      - "7. Hypothesis models": bayesian/lec7_hypothesis_models.md
      - "8. Loss functions": bayesian/lec8_loss_decisions.md
      - "9. Computational methods": bayesian/lec9_computation.md
      - "10. MCMC-Update": bayesian/lec10_mcmc.md
      - "11. Hierarchical Models": bayesian/lec11_hierarchy.md
  - History: history/index.md
